// src/lib/toolChecklists.js
// Fonte única dos checklists de ferramentas — mesmos itens da planilha Excel

export const TOOL_CHECKLISTS = {
  furadeira_impacto: {
    label: "Furadeira / Parafusadeira de Impacto",
    codigo: "SEG-FER-001",
    epis: ["Capacete de Segurança", "Óculos de Segurança", "Luva de Segurança", "Calçado de Segurança", "Protetor Auricular"],
    itens: [
      "O comutador (elétrica/bateria) está em bom estado de uso?",
      "A carcaça do equipamento está em boas condições, sem trincas ou rachaduras?",
      "O motor está livre de vibrações e ruídos anormais quando em funcionamento?",
      "O mandril está em boas condições de uso, sem partes quebradas ou folgas?",
      "Cabo elétrico em bom estado, sem emendas ou fios expostos (quando aplicável)?",
      "Bateria e carregador sem sinais de dano, inchaço, trincas ou superaquecimento (quando aplicável)?",
      "Chave liga/desliga (gatilho) mantém o equipamento em funcionamento somente quando pressionada?",
      "Manopla/empunhadeira lateral fixa e firme (quando existir)?",
      "Seletor de função (furar/parafusar/impacto) funcionando corretamente?",
      "Possui chave de mandril presa em local específico (quando aplicável)?",
      "As brocas/bits estão em boas condições de uso, sem trincas ou partes quebradas?",
    ],
  },
  parafusadeira_comum: {
    label: "Parafusadeira a Bateria",
    codigo: "SEG-FER-002",
    epis: ["Óculos de Segurança", "Luva de Segurança", "Calçado de Segurança"],
    itens: [
      "A carcaça está em boas condições, sem trincas ou rachaduras?",
      "A bateria está sem sinais de dano, inchaço, trincas ou superaquecimento?",
      "O carregador de bateria está em bom estado, sem fios expostos ou emendas?",
      "A chave liga/desliga (gatilho) funciona corretamente, sem travamento indevido?",
      "O seletor de torque/velocidade funciona corretamente?",
      "O reversor (sentido horário/anti-horário) funciona corretamente?",
      "O mandril/porta-bits está em boas condições, sem folgas?",
      "Os bits e acessórios estão em boas condições, sem desgaste excessivo?",
      "O equipamento está livre de vibrações e ruídos anormais durante o uso?",
    ],
  },
  esmerilhadeira_45: {
    label: 'Esmerilhadeira Angular 4.1/2"',
    codigo: "SEG-FER-003",
    epis: ["Capacete de Segurança", "Protetor Facial", "Óculos de Segurança", "Luva de Segurança", "Calçado de Segurança", "Protetor Auricular", "Avental de Raspa"],
    itens: [
      "A coifa/carcaça de proteção do disco está instalada e travada corretamente?",
      "O disco é compatível com a RPM da máquina e está sem trincas, empeno ou desgaste excessivo?",
      "Os flanges (superior e inferior) estão em boas condições e bem fixados?",
      "O botão de trava do eixo funciona corretamente?",
      "A empunhadeira lateral está instalada e firme?",
      "A chave liga/desliga está em boas condições, sem travamento indevido (sem trava em posição ligada)?",
      "O cabo elétrico/bateria está em bom estado, sem emendas ou fios expostos?",
      "A carcaça/corpo do equipamento está sem rachaduras ou trincas?",
      "O equipamento está livre de vibração/trepidação excessiva ao ligar?",
      "O disco utilizado é apropriado para a tarefa (corte ou desbaste)?",
    ],
  },
  esmerilhadeira_7: {
    label: 'Esmerilhadeira Angular 7"',
    codigo: "SEG-FER-004",
    epis: ["Capacete de Segurança", "Protetor Facial", "Óculos de Segurança", "Luva de Segurança", "Calçado de Segurança", "Protetor Auricular", "Avental de Raspa"],
    itens: [
      "A coifa/carcaça de proteção do disco está instalada e travada corretamente?",
      "O disco é compatível com a RPM da máquina e está sem trincas, empeno ou desgaste excessivo?",
      "Os flanges (superior e inferior) estão em boas condições e bem fixados?",
      "O botão de trava do eixo funciona corretamente?",
      "A empunhadeira lateral (uso obrigatório com as duas mãos) está instalada e firme?",
      "A chave liga/desliga está em boas condições, sem travamento indevido?",
      "O cabo elétrico está em bom estado, sem emendas ou fios expostos?",
      "A carcaça/corpo do equipamento está sem rachaduras ou trincas?",
      "As escovas de carvão estão sem desgaste excessivo (quando de fácil verificação)?",
      "O equipamento está livre de vibração/trepidação excessiva ao ligar?",
      "O aterramento está adequado, principalmente quando em uso com extensão elétrica?",
    ],
  },
  solda: {
    label: "Máquina de Solda (Inversora)",
    codigo: "SEG-FER-005",
    epis: ["Máscara de Solda", "Avental de Raspa", "Luva de Raspa", "Calçado de Segurança", "Óculos de Segurança", "Protetor Auricular"],
    itens: [
      "A carcaça está em bom estado, sem trincas, amassados ou sinais de vazamento?",
      "O cabo elétrico de alimentação está em bom estado de conservação (sem emendas expostas)?",
      "O plugue e a tomada estão em conformidade com a NR-10 (padrão macho/fêmea)?",
      "A chave liga/desliga está em boas condições de uso e funcionamento?",
      "A máquina possui cabo de aterramento conectado corretamente?",
      "O cabo do eletrodo (cabo guia) e suas conexões estão com isolamento íntegro, sem emendas?",
      'O alicate porta-eletrodo ("jacaré") está em boas condições, isolado e sem folga?',
      "A garra de aterramento (cabo terra/massa) está em bom estado de conservação?",
      "A peça a ser soldada está isenta de resíduos de óleo, graxa ou material inflamável nas proximidades?",
      "O painel/display e os botões de regulagem de amperagem funcionam corretamente?",
      "A ventilação/coifa de refrigeração do equipamento está desobstruída?",
      "As rodas/alça de transporte (quando houver) estão em bom estado?",
    ],
  },
  cinto_talabarte: {
    label: "Cinto Paraquedista com Talabarte Y",
    codigo: "SEG-EPI-001",
    epis: ["Capacete com Jugular", "Calçado de Segurança", "Luva de Segurança", "Óculos de Segurança"],
    // Equipamento de proteção contra queda: qualquer defeito = retirar de uso, então não existe "Parcialmente".
    statusOptions: ["C", "NC", "NA"],
    avisoNC: "Item não conforme: retirar o cinto/talabarte de uso imediatamente e comunicar o responsável.",
    itens: [
      "A etiqueta está legível, com CA válido, fabricante, lote e data de fabricação?",
      "O equipamento está dentro da vida útil indicada pelo fabricante e com a inspeção periódica em dia?",
      "O equipamento nunca reteve uma queda (indicador de queda não acionado)?",
      "As fitas do cinturão estão sem cortes, desfiamentos, abrasão, queimaduras, respingos de solda, ressecamento ou contaminação química?",
      "As costuras do cinturão estão íntegras, sem pontos rompidos ou soltos?",
      "As argolas (dorsal, peitoral e laterais) estão sem deformação, trincas, corrosão ou rebarbas?",
      "As fivelas de ajuste e engate travam corretamente, sem corrosão ou deformação?",
      "Os passadores, presilhas e acolchoamentos estão em bom estado (quando houver)?",
      "As duas pernas do talabarte Y estão sem cortes, desfiamentos, nós, abrasão, queimaduras ou ressecamento?",
      "As costuras e os terminais das duas pernas do talabarte estão íntegros?",
      "A capa do absorvedor de energia está íntegra e lacrada, sem rasgos nem sinal de abertura?",
      "As pernas elásticas do talabarte recolhem normalmente (quando aplicável)?",
      "Os mosquetões/ganchos estão sem trincas, deformação, corrosão ou desgaste?",
      "A trava de dupla ação dos conectores abre, fecha e trava sozinha, com a mola funcionando?",
      "A conexão do talabarte com o cinturão (argola dorsal ou peitoral) está correta e firme?",
      "O equipamento está limpo, seco e armazenado longe de sol, umidade e produtos químicos?",
    ],
  },
};

export const STATUS_OPTIONS = [
  { value: "C", label: "Conforme" },
  { value: "NC", label: "Não Conforme" },
  { value: "P", label: "Parcialmente" },
  { value: "NA", label: "Não se Aplica" },
];
