-- ============================================================
--  Backfill de falha_categoria  (atendimentos + inspecoes)
--  Gerado de src/lib/falhasPorMarca.js  --  rode UMA vez no SQL Editor do Supabase.
--  Idempotente e seguro: so escreve em linhas com falha_categoria nula/vazia.
--  Categorias validas: alimentacao, fiacao, dispositivo_desconectado, dispositivo_cadastro, detector_sujo, saida_nac, rede_paineis, sistema, anunciador, diagnostico
-- ============================================================
begin;

-- 1) Linhas que ja tem o codigo catalogado gravado: deriva a categoria do codigo.
with cat_por_codigo (codigo, categoria) as (values
  ('HOC-19', 'alimentacao'),
  ('HOC-20', 'alimentacao'),
  ('HOC-21', 'alimentacao'),
  ('HOC-24', 'alimentacao'),
  ('HOC-23', 'alimentacao'),
  ('HOC-05', 'dispositivo_desconectado'),
  ('HOC-15', 'fiacao'),
  ('HOC-18', 'fiacao'),
  ('HOC-17', 'fiacao'),
  ('HOC-16', 'fiacao'),
  ('HOC-02', 'dispositivo_desconectado'),
  ('HOC-10', 'dispositivo_cadastro'),
  ('HOC-06', 'dispositivo_cadastro'),
  ('HOC-07', 'saida_nac'),
  ('HOC-03', 'fiacao'),
  ('HOC-04', 'fiacao'),
  ('HOC-08', 'dispositivo_cadastro'),
  ('HOC-09', 'dispositivo_cadastro'),
  ('HOC-29', 'detector_sujo'),
  ('HOC-22', 'alimentacao'),
  ('HOC-44', 'rede_paineis'),
  ('HOC-40', 'rede_paineis'),
  ('HOC-45', 'rede_paineis'),
  ('HOC-46', 'rede_paineis'),
  ('HOC-50', 'rede_paineis'),
  ('HOC-51', 'rede_paineis'),
  ('HOC-70', 'anunciador'),
  ('HOC-69', 'dispositivo_desconectado'),
  ('HOC-36', 'dispositivo_cadastro'),
  ('HOC-37', 'dispositivo_cadastro'),
  ('HOC-25', 'sistema'),
  ('HOC-26', 'sistema'),
  ('HOC-00', 'sistema'),
  ('HOC-27', 'sistema'),
  ('HOC-35', 'dispositivo_cadastro'),
  ('HOC-34', 'dispositivo_cadastro'),
  ('HOC-33', 'dispositivo_cadastro'),
  ('HOC-38', 'rede_paineis'),
  ('HOC-39', 'rede_paineis'),
  ('HOC-41', 'rede_paineis'),
  ('HOC-42', 'rede_paineis'),
  ('HOC-43', 'rede_paineis'),
  ('HOC-47', 'rede_paineis'),
  ('HOC-52', 'rede_paineis'),
  ('HOC-54', 'rede_paineis'),
  ('HOC-68', 'dispositivo_cadastro'),
  ('HOC-71', 'dispositivo_cadastro'),
  ('HOC-49', 'sistema'),
  ('HOC-01', 'diagnostico'),
  ('HOC-11', 'diagnostico'),
  ('HOC-12', 'diagnostico'),
  ('HOC-13', 'diagnostico'),
  ('HOC-14', 'diagnostico'),
  ('HOC-30', 'diagnostico'),
  ('HOC-28', 'diagnostico'),
  ('HOC-31', 'diagnostico'),
  ('HOC-32', 'diagnostico'),
  ('HOC-48', 'diagnostico'),
  ('HOC-53', 'diagnostico'),
  ('HOC-55', 'diagnostico'),
  ('HOC-56', 'diagnostico'),
  ('HOC-57', 'diagnostico'),
  ('HOC-58', 'diagnostico'),
  ('HOC-59', 'diagnostico'),
  ('HOC-60', 'diagnostico'),
  ('HOC-61', 'diagnostico'),
  ('HOC-62', 'diagnostico'),
  ('HOC-63', 'diagnostico'),
  ('HOC-64', 'diagnostico'),
  ('HOC-65', 'diagnostico'),
  ('HOC-66', 'diagnostico'),
  ('HOC-67', 'diagnostico'),
  ('HOC-72', 'diagnostico'),
  ('HOC-73', 'diagnostico'),
  ('NOT-01', 'alimentacao'),
  ('NOT-02', 'alimentacao'),
  ('NOT-03', 'alimentacao'),
  ('NOT-04', 'alimentacao'),
  ('NOT-05', 'fiacao'),
  ('NOT-06', 'fiacao'),
  ('NOT-07', 'fiacao'),
  ('NOT-08', 'dispositivo_desconectado'),
  ('NOT-09', 'detector_sujo'),
  ('NOT-10', 'fiacao'),
  ('NOT-11', 'fiacao'),
  ('NOT-12', 'alimentacao'),
  ('NOT-13', 'saida_nac'),
  ('NOT-14', 'dispositivo_desconectado'),
  ('NOT-15', 'fiacao'),
  ('NOT-16', 'fiacao'),
  ('NOT-17', 'fiacao'),
  ('NOT-18', 'fiacao'),
  ('NOT-19', 'rede_paineis'),
  ('NOT-20', 'rede_paineis'),
  ('NOT-21', 'rede_paineis'),
  ('NOT-22', 'rede_paineis'),
  ('NOT-23', 'rede_paineis'),
  ('NOT-24', 'diagnostico'),
  ('NOT-25', 'dispositivo_desconectado'),
  ('NOT-26', 'alimentacao'),
  ('NOT-27', 'alimentacao'),
  ('NOT-28', 'diagnostico'),
  ('NOT-29', 'anunciador'),
  ('NOT-30', 'anunciador'),
  ('NOT-31', 'detector_sujo'),
  ('NOT-32', 'sistema'),
  ('NOT-33', 'sistema'),
  ('NOT-34', 'sistema'),
  ('NOT-35', 'sistema'),
  ('NOT-36', 'sistema'),
  ('NOT-37', 'alimentacao'),
  ('NOT-38', 'diagnostico'),
  ('NOT-39', 'diagnostico'),
  ('NOT-40', 'dispositivo_desconectado'),
  ('NOT-41', 'alimentacao'),
  ('NOT-42', 'rede_paineis'),
  ('NOT-43', 'rede_paineis'),
  ('NOT-44', 'diagnostico'),
  ('NOT-45', 'diagnostico'),
  ('NOT-46', 'sistema'),
  ('NOT-47', 'sistema'),
  ('NOT-48', 'sistema'),
  ('NOT-49', 'sistema'),
  ('NOT-50', 'sistema'),
  ('NOT-51', 'sistema'),
  ('NOT-52', 'sistema'),
  ('NOT-53', 'sistema'),
  ('NOT-54', 'alimentacao'),
  ('NOT-55', 'diagnostico'),
  ('NOT-56', 'alimentacao'),
  ('NOT-57', 'sistema'),
  ('NOT-58', 'dispositivo_desconectado'),
  ('NOT-59', 'dispositivo_desconectado'),
  ('NOT-60', 'dispositivo_desconectado'),
  ('NOT-61', 'saida_nac'),
  ('NOT-62', 'sistema'),
  ('NOT-63', 'diagnostico'),
  ('NOT-64', 'diagnostico'),
  ('NOT-65', 'diagnostico'),
  ('NOT-66', 'diagnostico'),
  ('NOT-67', 'diagnostico'),
  ('NOT-68', 'diagnostico'),
  ('NOT-69', 'diagnostico'),
  ('NOT-70', 'diagnostico'),
  ('NOT-71', 'diagnostico'),
  ('NOT-72', 'diagnostico')
)
update atendimentos a
   set falha_categoria = c.categoria
  from cat_por_codigo c
 where a.falha_codigo = c.codigo
   and coalesce(a.falha_categoria, '') = '';

with cat_por_codigo (codigo, categoria) as (values
  ('HOC-19', 'alimentacao'),
  ('HOC-20', 'alimentacao'),
  ('HOC-21', 'alimentacao'),
  ('HOC-24', 'alimentacao'),
  ('HOC-23', 'alimentacao'),
  ('HOC-05', 'dispositivo_desconectado'),
  ('HOC-15', 'fiacao'),
  ('HOC-18', 'fiacao'),
  ('HOC-17', 'fiacao'),
  ('HOC-16', 'fiacao'),
  ('HOC-02', 'dispositivo_desconectado'),
  ('HOC-10', 'dispositivo_cadastro'),
  ('HOC-06', 'dispositivo_cadastro'),
  ('HOC-07', 'saida_nac'),
  ('HOC-03', 'fiacao'),
  ('HOC-04', 'fiacao'),
  ('HOC-08', 'dispositivo_cadastro'),
  ('HOC-09', 'dispositivo_cadastro'),
  ('HOC-29', 'detector_sujo'),
  ('HOC-22', 'alimentacao'),
  ('HOC-44', 'rede_paineis'),
  ('HOC-40', 'rede_paineis'),
  ('HOC-45', 'rede_paineis'),
  ('HOC-46', 'rede_paineis'),
  ('HOC-50', 'rede_paineis'),
  ('HOC-51', 'rede_paineis'),
  ('HOC-70', 'anunciador'),
  ('HOC-69', 'dispositivo_desconectado'),
  ('HOC-36', 'dispositivo_cadastro'),
  ('HOC-37', 'dispositivo_cadastro'),
  ('HOC-25', 'sistema'),
  ('HOC-26', 'sistema'),
  ('HOC-00', 'sistema'),
  ('HOC-27', 'sistema'),
  ('HOC-35', 'dispositivo_cadastro'),
  ('HOC-34', 'dispositivo_cadastro'),
  ('HOC-33', 'dispositivo_cadastro'),
  ('HOC-38', 'rede_paineis'),
  ('HOC-39', 'rede_paineis'),
  ('HOC-41', 'rede_paineis'),
  ('HOC-42', 'rede_paineis'),
  ('HOC-43', 'rede_paineis'),
  ('HOC-47', 'rede_paineis'),
  ('HOC-52', 'rede_paineis'),
  ('HOC-54', 'rede_paineis'),
  ('HOC-68', 'dispositivo_cadastro'),
  ('HOC-71', 'dispositivo_cadastro'),
  ('HOC-49', 'sistema'),
  ('HOC-01', 'diagnostico'),
  ('HOC-11', 'diagnostico'),
  ('HOC-12', 'diagnostico'),
  ('HOC-13', 'diagnostico'),
  ('HOC-14', 'diagnostico'),
  ('HOC-30', 'diagnostico'),
  ('HOC-28', 'diagnostico'),
  ('HOC-31', 'diagnostico'),
  ('HOC-32', 'diagnostico'),
  ('HOC-48', 'diagnostico'),
  ('HOC-53', 'diagnostico'),
  ('HOC-55', 'diagnostico'),
  ('HOC-56', 'diagnostico'),
  ('HOC-57', 'diagnostico'),
  ('HOC-58', 'diagnostico'),
  ('HOC-59', 'diagnostico'),
  ('HOC-60', 'diagnostico'),
  ('HOC-61', 'diagnostico'),
  ('HOC-62', 'diagnostico'),
  ('HOC-63', 'diagnostico'),
  ('HOC-64', 'diagnostico'),
  ('HOC-65', 'diagnostico'),
  ('HOC-66', 'diagnostico'),
  ('HOC-67', 'diagnostico'),
  ('HOC-72', 'diagnostico'),
  ('HOC-73', 'diagnostico'),
  ('NOT-01', 'alimentacao'),
  ('NOT-02', 'alimentacao'),
  ('NOT-03', 'alimentacao'),
  ('NOT-04', 'alimentacao'),
  ('NOT-05', 'fiacao'),
  ('NOT-06', 'fiacao'),
  ('NOT-07', 'fiacao'),
  ('NOT-08', 'dispositivo_desconectado'),
  ('NOT-09', 'detector_sujo'),
  ('NOT-10', 'fiacao'),
  ('NOT-11', 'fiacao'),
  ('NOT-12', 'alimentacao'),
  ('NOT-13', 'saida_nac'),
  ('NOT-14', 'dispositivo_desconectado'),
  ('NOT-15', 'fiacao'),
  ('NOT-16', 'fiacao'),
  ('NOT-17', 'fiacao'),
  ('NOT-18', 'fiacao'),
  ('NOT-19', 'rede_paineis'),
  ('NOT-20', 'rede_paineis'),
  ('NOT-21', 'rede_paineis'),
  ('NOT-22', 'rede_paineis'),
  ('NOT-23', 'rede_paineis'),
  ('NOT-24', 'diagnostico'),
  ('NOT-25', 'dispositivo_desconectado'),
  ('NOT-26', 'alimentacao'),
  ('NOT-27', 'alimentacao'),
  ('NOT-28', 'diagnostico'),
  ('NOT-29', 'anunciador'),
  ('NOT-30', 'anunciador'),
  ('NOT-31', 'detector_sujo'),
  ('NOT-32', 'sistema'),
  ('NOT-33', 'sistema'),
  ('NOT-34', 'sistema'),
  ('NOT-35', 'sistema'),
  ('NOT-36', 'sistema'),
  ('NOT-37', 'alimentacao'),
  ('NOT-38', 'diagnostico'),
  ('NOT-39', 'diagnostico'),
  ('NOT-40', 'dispositivo_desconectado'),
  ('NOT-41', 'alimentacao'),
  ('NOT-42', 'rede_paineis'),
  ('NOT-43', 'rede_paineis'),
  ('NOT-44', 'diagnostico'),
  ('NOT-45', 'diagnostico'),
  ('NOT-46', 'sistema'),
  ('NOT-47', 'sistema'),
  ('NOT-48', 'sistema'),
  ('NOT-49', 'sistema'),
  ('NOT-50', 'sistema'),
  ('NOT-51', 'sistema'),
  ('NOT-52', 'sistema'),
  ('NOT-53', 'sistema'),
  ('NOT-54', 'alimentacao'),
  ('NOT-55', 'diagnostico'),
  ('NOT-56', 'alimentacao'),
  ('NOT-57', 'sistema'),
  ('NOT-58', 'dispositivo_desconectado'),
  ('NOT-59', 'dispositivo_desconectado'),
  ('NOT-60', 'dispositivo_desconectado'),
  ('NOT-61', 'saida_nac'),
  ('NOT-62', 'sistema'),
  ('NOT-63', 'diagnostico'),
  ('NOT-64', 'diagnostico'),
  ('NOT-65', 'diagnostico'),
  ('NOT-66', 'diagnostico'),
  ('NOT-67', 'diagnostico'),
  ('NOT-68', 'diagnostico'),
  ('NOT-69', 'diagnostico'),
  ('NOT-70', 'diagnostico'),
  ('NOT-71', 'diagnostico'),
  ('NOT-72', 'diagnostico')
)
update inspecoes i
   set falha_categoria = c.categoria
  from cat_por_codigo c
 where i.falha_codigo = c.codigo
   and coalesce(i.falha_categoria, '') = '';

-- 2) Linhas sem codigo, mas cujo texto de "falha" bate exatamente com o rotulo PT
--    de uma falha catalogada que mapeia p/ UMA unica categoria.
with cat_por_texto (pt, categoria) as (values
  ('falta de energia ca', 'alimentacao'),
  ('tensão de bateria baixa', 'alimentacao'),
  ('bateria desconectada', 'alimentacao'),
  ('falha no carregador', 'alimentacao'),
  ('falha no fusível de 24v auxiliar', 'alimentacao'),
  ('dispositivo desconectado', 'dispositivo_desconectado'),
  ('falha de terra', 'fiacao'),
  ('circuito aberto no laço', 'fiacao'),
  ('curto-circuito no laço', 'fiacao'),
  ('falha na fiação do laço', 'fiacao'),
  ('detector removido', 'dispositivo_desconectado'),
  ('tipo de dispositivo errado', 'dispositivo_cadastro'),
  ('endereço duplicado', 'dispositivo_cadastro'),
  ('falha na saída monitorada', 'saida_nac'),
  ('circuito aberto na linha escrava', 'fiacao'),
  ('curto-circuito na linha escrava', 'fiacao'),
  ('dispositivo desconhecido', 'dispositivo_cadastro'),
  ('dispositivo inesperado', 'dispositivo_cadastro'),
  ('falha na calibração', 'detector_sujo'),
  ('tensão de bateria muito alta', 'alimentacao'),
  ('circuito aberto ou curto na rede', 'rede_paineis'),
  ('nó de rede ausente', 'rede_paineis'),
  ('falha de comunicação na rede', 'rede_paineis'),
  ('timeout de comunicação na rede', 'rede_paineis'),
  ('comunicador ausente', 'rede_paineis'),
  ('falha de comunicação', 'rede_paineis'),
  ('anunciador ausente', 'anunciador'),
  ('placa de e/s ausente', 'dispositivo_desconectado'),
  ('módulo de e/s não instalado', 'dispositivo_cadastro'),
  ('módulo de e/s inesperado', 'dispositivo_cadastro'),
  ('watchdog do processador atuou', 'sistema'),
  ('falha de dados corrompidos', 'sistema'),
  ('problema interno', 'sistema'),
  ('evento de falha desconhecido', 'sistema'),
  ('limite de subendereços atingido', 'dispositivo_cadastro'),
  ('laço inesperado', 'dispositivo_cadastro'),
  ('laço não instalado', 'dispositivo_cadastro'),
  ('nó de rede inesperado', 'rede_paineis'),
  ('tipo de rede desconhecido', 'rede_paineis'),
  ('placa de rede inesperada', 'rede_paineis'),
  ('placa de rede não instalada', 'rede_paineis'),
  ('endereço da placa de rede incorreto', 'rede_paineis'),
  ('endereço de rede inválido', 'rede_paineis'),
  ('falha na linha telefônica 1', 'rede_paineis'),
  ('falha na linha telefônica 2', 'rede_paineis'),
  ('placa de e/s inesperada', 'dispositivo_cadastro'),
  ('desconhecido', 'sistema'),
  ('problema de manutenção', 'diagnostico'),
  ('inicializando dispositivo', 'diagnostico'),
  ('sistema inicializando', 'diagnostico'),
  ('autoaprendizagem (autolearn)', 'diagnostico'),
  ('nova configuração baixada do pc', 'diagnostico'),
  ('dispositivo inicializando', 'diagnostico'),
  ('pré-alarme', 'diagnostico'),
  ('entrada ativada', 'diagnostico'),
  ('causa e efeito ativo', 'diagnostico'),
  ('simulado de incêndio ativo', 'diagnostico'),
  ('linha telefônica 1 restaurada', 'diagnostico'),
  ('linha telefônica 2 restaurada', 'diagnostico'),
  ('dispositivo desabilitado', 'diagnostico'),
  ('zona desabilitada', 'diagnostico'),
  ('laço desabilitado', 'diagnostico'),
  ('todas as sirenes desabilitadas', 'diagnostico'),
  ('entrada do painel desabilitada', 'diagnostico'),
  ('saída do painel desabilitada', 'diagnostico'),
  ('desabilitação de causa e efeito (c&e)', 'diagnostico'),
  ('besouro (buzzer) desabilitado', 'diagnostico'),
  ('impressora desabilitada', 'diagnostico'),
  ('detecção de falha de terra desabilitada', 'diagnostico'),
  ('desabilitação (genérica)', 'diagnostico'),
  ('modo de teste', 'diagnostico'),
  ('teste de incêndio do sensor aprovado', 'diagnostico'),
  ('teste de incêndio do sensor reprovado', 'diagnostico'),
  ('falha de bateria', 'alimentacao'),
  ('falha na alimentação auxiliar', 'alimentacao'),
  ('falha de terra — laço 1', 'fiacao'),
  ('falha de terra — laço 2', 'fiacao'),
  ('dispositivo não responde', 'dispositivo_desconectado'),
  ('detector sujo', 'detector_sujo'),
  ('circuito aberto no módulo/alto-falante', 'fiacao'),
  ('curto-circuito', 'fiacao'),
  ('falha na fonte de alimentação', 'alimentacao'),
  ('nenhum dispositivo instalado no laço 1', 'dispositivo_desconectado'),
  ('falha polaridade positiva estilo 6 — laço 1', 'fiacao'),
  ('falha polaridade positiva estilo 6 — laço 2', 'fiacao'),
  ('falha polaridade negativa estilo 6 — laço 1', 'fiacao'),
  ('falha polaridade negativa estilo 6 — laço 2', 'fiacao'),
  ('falha de rede — porta a', 'rede_paineis'),
  ('falha de rede — porta b', 'rede_paineis'),
  ('falha de comunicação do módulo de rede (ncm)', 'rede_paineis'),
  ('falha no discador digital (udact)', 'rede_paineis'),
  ('discador digital (udact) não responde', 'rede_paineis'),
  ('condição supervisória ativa', 'diagnostico'),
  ('falha em módulo de controle/relé', 'dispositivo_desconectado'),
  ('carga da fonte auxiliar acima do normal', 'alimentacao'),
  ('carga da fonte auxiliar abaixo do normal', 'alimentacao'),
  ('porta do painel aberta', 'diagnostico'),
  ('falha no anunciador', 'anunciador'),
  ('anunciador não responde', 'anunciador'),
  ('temperatura abaixo do esperado no detector térmico', 'detector_sujo'),
  ('erro na eprom', 'sistema'),
  ('erro na memória ram interna', 'sistema'),
  ('erro na memória ram externa', 'sistema'),
  ('programação corrompida', 'sistema'),
  ('equação lógica corrompida', 'sistema'),
  ('falha na bateria de backup da ram', 'alimentacao'),
  ('supervisório no display lcd80', 'diagnostico'),
  ('supervisório no terminal', 'diagnostico'),
  ('falha na caixa mestra (master box)', 'dispositivo_desconectado'),
  ('falha de comunicação da fonte de alimentação', 'alimentacao'),
  ('rede incompatível', 'rede_paineis'),
  ('limite de conexões excedido', 'rede_paineis'),
  ('dispositivo de liberação (supressão) desabilitado', 'diagnostico'),
  ('ponto desabilitado manualmente', 'diagnostico'),
  ('autoteste do módulo de voz falhou', 'sistema'),
  ('incompatibilidade de software no módulo de voz', 'sistema'),
  ('programação do módulo de voz corrompida', 'sistema'),
  ('banco de dados do módulo de voz corrompido', 'sistema'),
  ('biblioteca de áudio do módulo de voz corrompida', 'sistema'),
  ('banco de dados do módulo de voz incompatível', 'sistema'),
  ('biblioteca de áudio do módulo de voz incompatível', 'sistema'),
  ('erro na ram externa do módulo de voz', 'sistema'),
  ('falha na bateria da nvram do módulo de voz', 'alimentacao'),
  ('besouro do módulo de voz fora de linha', 'diagnostico'),
  ('falha auxiliar no módulo de voz', 'alimentacao'),
  ('falha fft no módulo de voz', 'sistema'),
  ('falha no microfone remoto do módulo de voz', 'dispositivo_desconectado'),
  ('falha no microfone local do módulo de voz', 'dispositivo_desconectado'),
  ('falha no telefone local do módulo de voz', 'dispositivo_desconectado'),
  ('falha na saída analógica x do módulo de voz', 'saida_nac'),
  ('erro na imagem flash do módulo de voz', 'sistema'),
  ('módulo de voz carregando — fora de serviço', 'diagnostico'),
  ('download daa do módulo de voz em andamento', 'diagnostico'),
  ('modo "sniffer" do hs-ncm ativo', 'diagnostico'),
  ('modo de programação ativado', 'diagnostico'),
  ('carregando... fora de serviço', 'diagnostico'),
  ('teste de caminhada básico em andamento', 'diagnostico'),
  ('teste de caminhada avançado em andamento', 'diagnostico'),
  ('lembrete de 24h da nfpa', 'diagnostico'),
  ('detector inicializando', 'diagnostico'),
  ('simulado (drill) ativado', 'diagnostico')
)
update atendimentos a
   set falha_categoria = t.categoria
  from cat_por_texto t
 where coalesce(a.falha_codigo, '') = ''
   and coalesce(a.falha_categoria, '') = ''
   and lower(btrim(a.falha)) = t.pt;

with cat_por_texto (pt, categoria) as (values
  ('falta de energia ca', 'alimentacao'),
  ('tensão de bateria baixa', 'alimentacao'),
  ('bateria desconectada', 'alimentacao'),
  ('falha no carregador', 'alimentacao'),
  ('falha no fusível de 24v auxiliar', 'alimentacao'),
  ('dispositivo desconectado', 'dispositivo_desconectado'),
  ('falha de terra', 'fiacao'),
  ('circuito aberto no laço', 'fiacao'),
  ('curto-circuito no laço', 'fiacao'),
  ('falha na fiação do laço', 'fiacao'),
  ('detector removido', 'dispositivo_desconectado'),
  ('tipo de dispositivo errado', 'dispositivo_cadastro'),
  ('endereço duplicado', 'dispositivo_cadastro'),
  ('falha na saída monitorada', 'saida_nac'),
  ('circuito aberto na linha escrava', 'fiacao'),
  ('curto-circuito na linha escrava', 'fiacao'),
  ('dispositivo desconhecido', 'dispositivo_cadastro'),
  ('dispositivo inesperado', 'dispositivo_cadastro'),
  ('falha na calibração', 'detector_sujo'),
  ('tensão de bateria muito alta', 'alimentacao'),
  ('circuito aberto ou curto na rede', 'rede_paineis'),
  ('nó de rede ausente', 'rede_paineis'),
  ('falha de comunicação na rede', 'rede_paineis'),
  ('timeout de comunicação na rede', 'rede_paineis'),
  ('comunicador ausente', 'rede_paineis'),
  ('falha de comunicação', 'rede_paineis'),
  ('anunciador ausente', 'anunciador'),
  ('placa de e/s ausente', 'dispositivo_desconectado'),
  ('módulo de e/s não instalado', 'dispositivo_cadastro'),
  ('módulo de e/s inesperado', 'dispositivo_cadastro'),
  ('watchdog do processador atuou', 'sistema'),
  ('falha de dados corrompidos', 'sistema'),
  ('problema interno', 'sistema'),
  ('evento de falha desconhecido', 'sistema'),
  ('limite de subendereços atingido', 'dispositivo_cadastro'),
  ('laço inesperado', 'dispositivo_cadastro'),
  ('laço não instalado', 'dispositivo_cadastro'),
  ('nó de rede inesperado', 'rede_paineis'),
  ('tipo de rede desconhecido', 'rede_paineis'),
  ('placa de rede inesperada', 'rede_paineis'),
  ('placa de rede não instalada', 'rede_paineis'),
  ('endereço da placa de rede incorreto', 'rede_paineis'),
  ('endereço de rede inválido', 'rede_paineis'),
  ('falha na linha telefônica 1', 'rede_paineis'),
  ('falha na linha telefônica 2', 'rede_paineis'),
  ('placa de e/s inesperada', 'dispositivo_cadastro'),
  ('desconhecido', 'sistema'),
  ('problema de manutenção', 'diagnostico'),
  ('inicializando dispositivo', 'diagnostico'),
  ('sistema inicializando', 'diagnostico'),
  ('autoaprendizagem (autolearn)', 'diagnostico'),
  ('nova configuração baixada do pc', 'diagnostico'),
  ('dispositivo inicializando', 'diagnostico'),
  ('pré-alarme', 'diagnostico'),
  ('entrada ativada', 'diagnostico'),
  ('causa e efeito ativo', 'diagnostico'),
  ('simulado de incêndio ativo', 'diagnostico'),
  ('linha telefônica 1 restaurada', 'diagnostico'),
  ('linha telefônica 2 restaurada', 'diagnostico'),
  ('dispositivo desabilitado', 'diagnostico'),
  ('zona desabilitada', 'diagnostico'),
  ('laço desabilitado', 'diagnostico'),
  ('todas as sirenes desabilitadas', 'diagnostico'),
  ('entrada do painel desabilitada', 'diagnostico'),
  ('saída do painel desabilitada', 'diagnostico'),
  ('desabilitação de causa e efeito (c&e)', 'diagnostico'),
  ('besouro (buzzer) desabilitado', 'diagnostico'),
  ('impressora desabilitada', 'diagnostico'),
  ('detecção de falha de terra desabilitada', 'diagnostico'),
  ('desabilitação (genérica)', 'diagnostico'),
  ('modo de teste', 'diagnostico'),
  ('teste de incêndio do sensor aprovado', 'diagnostico'),
  ('teste de incêndio do sensor reprovado', 'diagnostico'),
  ('falha de bateria', 'alimentacao'),
  ('falha na alimentação auxiliar', 'alimentacao'),
  ('falha de terra — laço 1', 'fiacao'),
  ('falha de terra — laço 2', 'fiacao'),
  ('dispositivo não responde', 'dispositivo_desconectado'),
  ('detector sujo', 'detector_sujo'),
  ('circuito aberto no módulo/alto-falante', 'fiacao'),
  ('curto-circuito', 'fiacao'),
  ('falha na fonte de alimentação', 'alimentacao'),
  ('nenhum dispositivo instalado no laço 1', 'dispositivo_desconectado'),
  ('falha polaridade positiva estilo 6 — laço 1', 'fiacao'),
  ('falha polaridade positiva estilo 6 — laço 2', 'fiacao'),
  ('falha polaridade negativa estilo 6 — laço 1', 'fiacao'),
  ('falha polaridade negativa estilo 6 — laço 2', 'fiacao'),
  ('falha de rede — porta a', 'rede_paineis'),
  ('falha de rede — porta b', 'rede_paineis'),
  ('falha de comunicação do módulo de rede (ncm)', 'rede_paineis'),
  ('falha no discador digital (udact)', 'rede_paineis'),
  ('discador digital (udact) não responde', 'rede_paineis'),
  ('condição supervisória ativa', 'diagnostico'),
  ('falha em módulo de controle/relé', 'dispositivo_desconectado'),
  ('carga da fonte auxiliar acima do normal', 'alimentacao'),
  ('carga da fonte auxiliar abaixo do normal', 'alimentacao'),
  ('porta do painel aberta', 'diagnostico'),
  ('falha no anunciador', 'anunciador'),
  ('anunciador não responde', 'anunciador'),
  ('temperatura abaixo do esperado no detector térmico', 'detector_sujo'),
  ('erro na eprom', 'sistema'),
  ('erro na memória ram interna', 'sistema'),
  ('erro na memória ram externa', 'sistema'),
  ('programação corrompida', 'sistema'),
  ('equação lógica corrompida', 'sistema'),
  ('falha na bateria de backup da ram', 'alimentacao'),
  ('supervisório no display lcd80', 'diagnostico'),
  ('supervisório no terminal', 'diagnostico'),
  ('falha na caixa mestra (master box)', 'dispositivo_desconectado'),
  ('falha de comunicação da fonte de alimentação', 'alimentacao'),
  ('rede incompatível', 'rede_paineis'),
  ('limite de conexões excedido', 'rede_paineis'),
  ('dispositivo de liberação (supressão) desabilitado', 'diagnostico'),
  ('ponto desabilitado manualmente', 'diagnostico'),
  ('autoteste do módulo de voz falhou', 'sistema'),
  ('incompatibilidade de software no módulo de voz', 'sistema'),
  ('programação do módulo de voz corrompida', 'sistema'),
  ('banco de dados do módulo de voz corrompido', 'sistema'),
  ('biblioteca de áudio do módulo de voz corrompida', 'sistema'),
  ('banco de dados do módulo de voz incompatível', 'sistema'),
  ('biblioteca de áudio do módulo de voz incompatível', 'sistema'),
  ('erro na ram externa do módulo de voz', 'sistema'),
  ('falha na bateria da nvram do módulo de voz', 'alimentacao'),
  ('besouro do módulo de voz fora de linha', 'diagnostico'),
  ('falha auxiliar no módulo de voz', 'alimentacao'),
  ('falha fft no módulo de voz', 'sistema'),
  ('falha no microfone remoto do módulo de voz', 'dispositivo_desconectado'),
  ('falha no microfone local do módulo de voz', 'dispositivo_desconectado'),
  ('falha no telefone local do módulo de voz', 'dispositivo_desconectado'),
  ('falha na saída analógica x do módulo de voz', 'saida_nac'),
  ('erro na imagem flash do módulo de voz', 'sistema'),
  ('módulo de voz carregando — fora de serviço', 'diagnostico'),
  ('download daa do módulo de voz em andamento', 'diagnostico'),
  ('modo "sniffer" do hs-ncm ativo', 'diagnostico'),
  ('modo de programação ativado', 'diagnostico'),
  ('carregando... fora de serviço', 'diagnostico'),
  ('teste de caminhada básico em andamento', 'diagnostico'),
  ('teste de caminhada avançado em andamento', 'diagnostico'),
  ('lembrete de 24h da nfpa', 'diagnostico'),
  ('detector inicializando', 'diagnostico'),
  ('simulado (drill) ativado', 'diagnostico')
)
update inspecoes i
   set falha_categoria = t.categoria
  from cat_por_texto t
 where coalesce(i.falha_codigo, '') = ''
   and coalesce(i.falha_categoria, '') = ''
   and lower(btrim(i.falha)) = t.pt;

commit;
-- (troque por  rollback;  se quiser abortar antes de confirmar)

-- 3) Relatorio pos-backfill: o que ainda sobra sem categoria
--    (exatamente o que continua caindo em "Nao classificado" no card do Dashboard).
select 'atendimentos s/ categoria' as alvo, count(*) as qtd
  from atendimentos
 where coalesce(falha, '') not in ('', 'Realizado sem apontamentos')
   and coalesce(falha_categoria, '') = ''
union all
select 'inspecoes s/ categoria', count(*)
  from inspecoes
 where coalesce(falha, '') <> ''
   and coalesce(falha_categoria, '') = '';

-- Rotulos PT ambiguos (2+ categorias) ficaram de fora do passo 2, classifique na mao se aparecerem:
--   (nenhum)
